import Banner from "@/marcham/components/banner/Banner";
import React from "react";
import banner from "../../assets/banner/contactbanner.png";
import bannermob from "../../assets/banner/contactbannermob.png";
import Contact from "@/marcham/components/contact/Contact";
import Map from "@/marcham/components/map/Map";
export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <>
      <Banner
        banner={banner}
        mobilebanner={bannermob}
        text="Get in Touch with Our Cricket Experts"
      />
      {/* contact */}
      <Contact />
      {/* map */}
      <Map />
    </>
  );
};

export default page;
