import Banner from "@/marcham/components/banner/Banner";
import React from "react";
import banner from "../../assets/banner/coachesbanner.png";
import bannermob from "../../assets/banner/coachesbannermob.png";
import coaches from "../../assets/coache.png";
import Image from "next/image";
import Button from "@/UI/redbutton/Button";
import srilanka from "../../assets/srilanka.png";
import players from "../../assets/players.png";
import messageblue from "../../assets/messageblue.png";
import message from "../../assets/messageicon.png";
import CoachTestimonial from "@/UI/slider/CoachTestimonial";
export const metadata = {
  title: "Coaches",
  description: "Generated by create next app",
};
const pages = () => {
  return (
    <>
      <Banner
        banner={banner}
        mobilebanner={bannermob}
        text="Transformative Coaching for Your Best Self"
      />
      {/* coaches */}
      <section className="section_top">
        <div className="container">
          <div className="grid-2-to-2 gap5">
            <div>
              <h2 className="title text-blue rocket">Head coach</h2>
              <h3 className="middletext text-red lg-text-center">
                Hasantha Mendis
              </h3>
              <div className="mobileview">
                <Image
                  src={coaches}
                  alt="cricket player"
                  className="img-fluid block margin-auto"
                />
              </div>
              <p className="paragraph text-gray justify-center mt-2">
                Lorem ipsum dolor sit amet consectetur. Et ante imperdiet
                porttitor vulputate id. Ultrices id lectus lectus consequat
                porttitor lobortis. Morbi sit nunc eleifend magna ornare enim.
                Non malesuada amet pulvinar mus. Diam massa ac eget mauris. Mi
                ut enim in egestas massa. Bibendum nec rutrum sed commodo.
              </p>
              {/* <div className="mt-2 mobile-flex-center">
                <Button>VIEW MORE</Button>
              </div> */}
            </div>
            <div className="desktopview">
              <Image src={coaches} alt="cricket player" className="img-fluid" />
            </div>
          </div>
        </div>
      </section>
      {/* srilanka */}
      <section className="section_top ">
        <div className="container">
          <div className="sectionpadingfull bg3">
            <div className="grid_1_to_2 gap5">
              <div className="desktopview">
                <Image
                  src={srilanka}
                  alt="cricket player"
                  className="img-fluid block margin-auto"
                />
              </div>
              <div>
                <h2 className="title text-blue rocket">
                  Playing Career Highlights
                </h2>
                <div className="mobileview mt-2">
                  <Image
                    src={srilanka}
                    alt="cricket player"
                    className="img-fluid block margin-auto"
                  />
                </div>
                <p className="paragraph text-gray justify-center mt-2">
                  Lorem ipsum dolor sit amet consectetur. Et ante imperdiet
                  porttitor vulputate id. Ultrices id lectus lectus consequat
                  porttitor lobortis. Morbi sit nunc eleifend magna ornare enim.
                  Non malesuada amet pulvinar mus. Diam massa ac eget mauris. Mi
                  ut enim in egestas massa. Bibendum nec rutrum sed commodo.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* Coaching Philosophy */}
      <section className="section_top">
        <div className="container">
          <div className="grid_2_to_1 gap5">
            <div>
              <h2 className="title text-blue rocket">Coaching Philosophy</h2>
              <p className="paragraph text-gray justify-center mt-2">
                Lorem ipsum dolor sit amet consectetur. Et ante imperdiet
                porttitor vulputate id. Ultrices id lectus lectus consequat
                porttitor lobortis. Morbi sit nunc eleifend magna ornare enim.
                Non malesuada amet pulvinar mus. Diam massa ac eget mauris. Mi
                ut enim in egestas massa. Bibendum nec rutrum sed commodo.
              </p>
            </div>
            <div>
              <Image
                src={players}
                alt="cricket player"
                className="img-fluid block margin-auto"
              />
            </div>
          </div>
        </div>
      </section>
      {/* coach team */}
      <section className="section_top">
        <div className="container">
          <h2 className="title text-blue rocket text-center">
            Coaching Specialization
          </h2>
          <p className="paragraph text-gray text-center mt-2">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium
            optio nobis fugit tempore magni quia, sequi molestias unde numquam
            velit beatae laboriosam cum ipsa a, voluptate enim harum. Quisquam,
            minima.
          </p>
          <p className="paragraph text-gray text-center mt-2">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium
            optio nobis fugit tempore magni quia, sequi molestias unde numquam
            velit beatae laboriosam cum ipsa a, voluptate enim harum. Quisquam,
            minima.
          </p>
          <p className="paragraph text-gray text-center mt-2">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium
            optio nobis fugit tempore magni quia, sequi molestias unde numquam
            velit beatae laboriosam cum ipsa a, voluptate enim harum. Quisquam,
            minima.
          </p>
        </div>
      </section>
      {/* testimonial */}
      <section className="section_top testpos">
        <div className="container">
          <div className="sectionpadingfull bg3">
            <div className="desktopview">
              <Image
                src={messageblue}
                alt="cricket player"
                className="messageiconblue"
              />
            </div>
            <h2 className="title text-blue rocket text-center">Testimonials</h2>
            <div className="inner-margin">
              <CoachTestimonial />
            </div>
            <div className="desktopview">
              <Image
                src={message}
                alt="cricket player"
                className="messageiconnew"
              />
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default pages;
