import Banner from "@/marcham/components/banner/Banner";
import React from "react";
import banner from "../../assets/banner/teambanner.png";
import bannermob from "../../assets/banner/testimonialBannermob.png";
import { testimonialialDetails } from "@/marcham/db/testimonialDetails";
import startImg from "../../assets/star.png";
import Image from "next/image";
import male from "../../assets/male.png";
import female from "../../assets/female.png";
export const metadata = {
  title: "Testimonials",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <>
      <Banner
        banner={banner}
        mobilebanner={bannermob}
        text="Meet Our Cricket Stars in Training Today"
      />
      {/* testimonials */}
      <section className="section_top">
        <div className="container">
          <h1 className="title text-blue rocket text-center">
            what our players says about us
          </h1>
          <div className="inner-margin">
            <div className="testimonial-grid">
              {testimonialialDetails.map((item) => (
                <div key={item.id} className=" testimonialItemnew">
                  <div className="flex  align-center gap-1">
                    {Array.from({ length: item.star }).map((_, index) => (
                      <Image key={index} src={startImg} alt="star" />
                    ))}
                  </div>
                  <p className="smalltext text-gray mt-2">{item.description}</p>
                  <div className="mt-2 flex align-center gap2">
                    <Image
                      src={item.gender === "male" ? male : female}
                      alt="team image"
                      className="gendernew"
                    />
                    <div>
                      <h3 className="middletext text-player ">{item.name}</h3>
                      <p className="smalltext text-gray">{item.player}</p>
                    </div>
                  </div>
                  <div className="testimonialout"></div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default page;
